version: '3.8'
services:
    db:
        image: mariadb:10.6
        container_name: perdin_db
        restart: unless-stopped
        environment:
            MARIADB_DATABASE: 'perdin_db'
            MARIADB_USER: 'perdin_user'
            MARIADB_PASSWORD: 'perdin_pass'
            MARIADB_ROOT_PASSWORD: 'root'
        ports:
            - '3306:3306'
        volumes:
            - my-db:/var/lib/mysql
        networks:
            - perdin_network
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: perdin_phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: perdin_user
            PMA_PASSWORD: perdin_pass
        ports:
            - "8081:80"
        depends_on:
            - db
        networks:
            - perdin_network
volumes:
    my-db:
        driver: local
networks:
    perdin_network:
        driver: bridge
